### ISSUE TITLE
Input_Box（プロンプトテキストボックスの開発

### ISSUE THREAD

**Issue by mtureit** [takumi0616/gpt-logprobs#20]
# 概要
プロンプトを入力するinputboxを開発する
# 開発目的
プロンプトを入力するため
# 考えられる開発内容
以下の2つのファイルを編集する
- next/app/components/common/InputBox/InputBox.tsx
- next/app/components/common/InputBox/InputBox.module.css

# 備考

**Comment by takumi0616** [comment]
@mtureit 
直して欲しいところ
- プロンプト入れるテキストエリアとGenerateButtonが横に配置されている
縦にして欲しい
![image](https://github.com/user-attachments/assets/6d15e11c-ffb7-42a3-bd27-150775b23804)

- テキストエリアの横幅が短い
これはGenerateButtonと横配置してるため、縦配置にすると治るはず

- 大量のテキストが入った際に、縦幅が設定されているため下に伸びない
大量に文字を入れた場合は縦幅がある一定（今の縦幅の4倍くらい）までは伸びるようにして欲しい

- react-iconsを導入してアイコンの設置もお願いします
歯車アイコンとファイルアイコン
